<?php
header("Access-Control-Allow-Origin: *");
header('Access-Control-Allow-Headers: Content-Type, x-xsrf-token');
header("content-type: application/json");

echo  '{"data":[
    {
        "id":1,
        "titleKg":"Мэр города Бишкек Албек Ибраимов принял участие в гарнизонном разводе столичной милиции",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/1.png",
        "thumbnailM":"dist\/assets\/img\/posts\/1.png",
        "thumbnailL":"dist\/assets\/img\/posts\/1.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":2,
        "titleKg":"Ленинский акимиат поздравил детей с ОВЗ с наступающим Новым Годом",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/2.png",
        "thumbnailM":"dist\/assets\/img\/posts\/2.png",
        "thumbnailL":"dist\/assets\/img\/posts\/2.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":3,
        "titleKg":"В Бишкеке открылась фотовыставка «Бишкек – мой любимый город!»",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/3.png",
        "thumbnailM":"dist\/assets\/img\/posts\/3.png",
        "thumbnailL":"dist\/assets\/img\/posts\/3.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":4,
        "titleKg":"Столичная мэрия поздравила энергетиков с профессиональным праздником",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/4.png",
        "thumbnailM":"dist\/assets\/img\/posts\/4.png",
        "thumbnailL":"dist\/assets\/img\/posts\/4.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":5,
        "titleKg":"Столичная мэрия провела обсуждение предварительных итогов работы за год и перспектив развития столицы",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/5.png",
        "thumbnailM":"dist\/assets\/img\/posts\/5.png",
        "thumbnailL":"dist\/assets\/img\/posts\/5.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":6,
        "titleKg":"В Бишкеке продолжаются встречи школьников в рамках проекта «Жаш Карек».",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/6.png",
        "thumbnailM":"dist\/assets\/img\/posts\/6.png",
        "thumbnailL":"dist\/assets\/img\/posts\/6.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    }
  

    ]}';
?>

