<?php
header("Access-Control-Allow-Origin: *");
header('Access-Control-Allow-Headers: Content-Type, x-xsrf-token');
header("content-type: application/json");

echo  '{"data":[
    {
        "id":1,
        "titleKg":"В столице Кыргызстана проходит новогоднее шествие Дед Морозов и Снегурочек",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/1.png",
        "thumbnailM":"dist\/assets\/img\/posts\/1.png",
        "thumbnailL":"dist\/assets\/img\/posts\/1.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":2,
        "titleKg":"Праздничное шествие дедов морозов",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/2.png",
        "thumbnailM":"dist\/assets\/img\/posts\/2.png",
        "thumbnailL":"dist\/assets\/img\/posts\/2.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":3,
        "titleKg":"Иса Омуркулов вручил ветеранам ВОВ ключи от однокомнатных квартир в центре Бишкека",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/3.png",
        "thumbnailM":"dist\/assets\/img\/posts\/3.png",
        "thumbnailL":"dist\/assets\/img\/posts\/3.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":4,
        "titleKg":"Квартиры для участников ВОВ",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/4.png",
        "thumbnailM":"dist\/assets\/img\/posts\/4.png",
        "thumbnailL":"dist\/assets\/img\/posts\/4.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":5,
        "titleKg":"Определились победители Кубка мэра города Бишкек по спортивным соревнованиям",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/5.png",
        "thumbnailM":"dist\/assets\/img\/posts\/5.png",
        "thumbnailL":"dist\/assets\/img\/posts\/5.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    },
    {
        "id":6,
        "titleKg":"Сегодня состоялось заседание рабочей комиссии по средствам наружной рекламы на территории города Бишкек.",
        "titleRu":"dfgdf",
        "titleEn":"Title on English 222333",
        "descKg":"222333",
        "descEn":"Short description 222333",
        "contentKg":" 222333",
        "contentRu":" 222333",
        "contentEn":"Full content 222333",
        "thumbnailS":"dist\/assets\/img\/posts\/6.png",
        "thumbnailM":"dist\/assets\/img\/posts\/6.png",
        "thumbnailL":"dist\/assets\/img\/posts\/6.png",
        "thumbdescKg":"dfgdfg",
        "thumbdescRu":"dfgh",
        "thumbdescEn":"Image","category":1,
        "owner":3,
        "slug":"four-post",
        "viewed":98,
        "status":0,
        "created_at":"2017-12-19 04:12:03",
        "updated_at":"2017-12-19 04:12:03"
    }
  

        ]}';
?>

